# Generated by Django 4.0.1 on 2025-03-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=255)),
                ('salt', models.CharField(default=1, max_length=222)),
            ],
        ),
    ]
