# Generated by Django 4.0.1 on 2025-03-21 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_Name', models.CharField(max_length=255)),
                ('Owner_Name', models.CharField(max_length=255)),
                ('Logo', models.FileField(null=True, upload_to='media/img')),
                ('Bus_Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=6)),
                ('district', models.CharField(max_length=255)),
                ('Business_type', models.CharField(max_length=255)),
                ('Registration_stat', models.CharField(max_length=255)),
                ('Reg_doc', models.FileField(upload_to='uploads/')),
                ('Login_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cusreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cus_Name', models.CharField(max_length=255)),
                ('Profile_pic', models.FileField(null=True, upload_to='media/img')),
                ('Cus_Email', models.CharField(max_length=255)),
                ('Contact', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=6)),
                ('district', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=1000)),
                ('Login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_Name', models.CharField(max_length=255)),
                ('Prod_cat', models.CharField(max_length=255)),
                ('Prod_des', models.CharField(max_length=255)),
                ('Prod_price', models.FloatField(max_length=10)),
                ('Availability', models.CharField(max_length=255)),
                ('Prod_image', models.FileField(null=True, upload_to='media/img')),
                ('Busreg', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.busreg')),
            ],
        ),
        migrations.CreateModel(
            name='Servicecat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serv_catname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serv_cat', models.CharField(max_length=255)),
                ('Serv_charge', models.FloatField(max_length=10)),
                ('Busreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.busreg')),
            ],
        ),
        migrations.CreateModel(
            name='Servfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.CharField(max_length=255)),
                ('Message', models.CharField(max_length=255)),
                ('Feedbacktime', models.DateField()),
                ('Busreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.busreg')),
                ('Cusreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cusreg')),
                ('Services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offer_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('Discount', models.CharField(blank=True, max_length=255, null=True)),
                ('Start_date', models.DateField(null=True)),
                ('End_date', models.DateField(null=True)),
                ('Products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.CharField(max_length=255)),
                ('Message', models.CharField(max_length=255)),
                ('Feedbacktime', models.DateField()),
                ('Busreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.busreg')),
                ('Cusreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cusreg')),
                ('Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Queries', models.CharField(max_length=255)),
                ('Busreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.busreg')),
                ('Cusreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cusreg')),
                ('Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Off_web', models.CharField(max_length=255)),
                ('Linkedin', models.CharField(max_length=255)),
                ('Social', models.CharField(max_length=255)),
                ('Busreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.busreg')),
            ],
        ),
    ]
