# Generated by Django 4.0.1 on 2025-03-21 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_busreg_category_cusreg_products_servicecat_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servfeedback',
            name='Busreg',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.CASCADE, to='myapp.busreg'),
        ),
        migrations.AlterField(
            model_name='servfeedback',
            name='Cusreg',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='myapp.cusreg'),
        ),
        migrations.AlterField(
            model_name='servfeedback',
            name='Services',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='myapp.services'),
        ),
    ]
