# Generated by Django 4.0.1 on 2025-04-22 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_roomimage_saveddesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddesign',
            name='Cusreg',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.cusreg'),
        ),
    ]
