# Generated by Django 4.0.1 on 2025-04-25 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_saveddesign_cusreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='Serv_charge',
        ),
        migrations.AddField(
            model_name='services',
            name='Serv_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='Busreg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.busreg'),
        ),
        migrations.AlterField(
            model_name='services',
            name='Serv_cat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
